#+title: vega-lite: A [WIP] Common Lisp interface for Vega Lite

#+begin_quote
The state of vega-lite(-wip) is very much experimental. However, experimentation seems to be the only way to move forward.
#+end_quote

In case you haven't used, [[https://ggplot2.tidyverse.org/][ggplot]], you should definitely try! The magic seems to be due to [[https://en.wikipedia.org/wiki/Wilkinson%27s_Grammar_of_Graphics][grammar of graphics]]. [[https://vega.github.io/vega-lite/][vega-lite]] takes inspiration to this and adds to it to build a grammar of interactive grammar of graphics. To quote the wiki:

#+begin_quote
*Grammar of Graphics* (GoG) is a grammar-based system for representing graphics to provide grammatical constraints on the composition of data and information visualizations. A graphical grammar differs from a graphics pipeline as it focuses on sematic components such as scales and guides, statistical functions, coordinate systems, marks and aesthetic attributes.^{[[https://en.wikipedia.org/wiki/Wilkinson's_Grammar_of_Graphics#cite_note-:3-1][(1)]]}^{[[https://en.wikipedia.org/wiki/Wilkinson's_Grammar_of_Graphics#cite_note-:1-2][(2)]]} For example, a [[https://en.wikipedia.org/wiki/Bar_chart][bar chart]] can be converted into a [[https://en.wikipedia.org/wiki/Pie_chart][pie chart]] by specifying a [[https://en.wikipedia.org/wiki/Polar_coordinate_system][polar coordinate system]] without any other change in graphical specification.:^{[[https://en.wikipedia.org/wiki/Wilkinson's_Grammar_of_Graphics#cite_note-:3-1][(1)]]}^{[[https://en.wikipedia.org/wiki/Wilkinson's_Grammar_of_Graphics#cite_note-:0-3][(3)]]}
#+end_quote

The current library =cl-vega-lite= is a Common Lisp interface to [[https://vega.github.io/vega-lite/][vega-lite]]. It provides ="vega-lite-wip"= asdf system, loading which creates the package =vega-lite= with all the below functionality. Out of the box, it works for up to about 1000 points, and may be 10000 points if you can tolerate some lag. Beyond that, you would need to do manual simplification.

I know of exactly one lisp attempt at doing something similar: [[https://github.com/Lisp-Stat/plot/][plot]]. However, compared to =plot/vega=, I intend to keep dependencies simpler. In particular, the only dependencies are:

- hunchensocket: vega-lite is a JS library, so we use the browser; and use bidirectional communication to obtain svg and png files
- closer-mop: introspecting CLOS to ease usage
- shasht: because JS loves JSON and I love shasht
- alexandria

Furthermore, the goal is to use the rich assertion and type system of Common Lisp to allow stronger checks and helps before the JSON reaches the browser, and minimize the /overgenerosity/ of JS interpreters. With SBCL, this can be achieved by compiling the system with =(declaim (optimize speed))=, however, making sure the library works as expected with this stronger type checking is still a work in progress. At a minimum, my expectation is that CLOS and spec objects are easier to work with that manipulating JSON.

* Contents
:PROPERTIES:
:TOC:      :include all :ignore (this)
:END:

:CONTENTS:
- [[#installation][Installation]]
- [[#getting-started][Getting Started]]
  - [[#fast-to-get-started-high-level-rigid-wip][Fast to get started, high-level, rigid (WIP)]]
  - [[#grammatical-mid-level-wip][Grammatical, mid-level (WIP)]]
  - [[#ugly-low-level-flexible-vega-plot-specification][Ugly, low-level, flexible: (vega-plot specification)]]
- [[#interactive-example][Interactive Example]]
- [[#common-issues][Common Issues]]
  - [[#error-message-fragment-too-big][Error: Message fragment too big]]
:END:

* Installation
:PROPERTIES:
:CUSTOM_ID: installation
:END:

Install [[https://github.com/rudolfochrist/ql-https][ql-https]]:

#+begin_src
export LISP=sbcl
curl https://raw.githubusercontent.com/rudolfochrist/ql-https/master/install.sh | bash
#+end_src

Install [[https://ultralisp.org/][ultralisp]]:

#+begin_src lisp
(ql-dist:install-dist "http://dist.ultralisp.org/"
                      :prompt nil)
#+end_src

Install vega-lite:

#+begin_src lisp
(ql:quickload "vega-lite-wip")
#+end_src

* Getting Started
:PROPERTIES:
:CUSTOM_ID: getting-started
:END:

After installation, you can use package local nicknames to use it in your own package.

#+begin_src lisp
(defpackage :vega-lite-user
  (:use :cl)
  (:local-nicknames (:vl :vega-lite)))

(in-package :vega-lite-user)

(vl:ensure-plot-server)
#+end_src

There are three ways to use vega-lite.

** Fast to get started, high-level, rigid (WIP)
:PROPERTIES:
:CUSTOM_ID: fast-to-get-started-high-level-rigid-wip
:END:

- bar-chart
- histogram
- scatter

Out of the box, support is provided for plotting when data is supplied as 1 dimensional lists or vectors. For other data types, specialize the =1d-data-as-list= method.

** Grammatical, mid-level (WIP)
:PROPERTIES:
:CUSTOM_ID: grammatical-mid-level-wip
:END:

The mid level API maps CLOS classes onto the corresponding vega-lite specifications. At the highest level is the [[file:src/spec.lisp][spec class]]; all other classes within this library are subclasses of the =spec= class. Each object that is an instance of these classes also have a =depth= slot which specifies the JSON depth of the specification corresponding to that object.

Main functions and variables:

- make-plot
- save-plot
- vega-compose
- =*plot-on-compose*=

=vega-compose= takes in a list of elements and combines them. Essentially, it reduces using the function =compose=. It takes two arguments, and combines them /reasonably/.

To see example uses of these, refer [[file:src/high-level.lisp][src/high-level.lisp]] as well as the [[file:docs/taming-vega-lite.org][Taming Vega Lite]] short read.

Other constructors - almost all of them have corresponding classes:

- make-concat
- make-data
- make-datasets
- make-mark
- make-param
- make-select

- make-encoding
- make-x
- make-y
- make-x2
- make-y2
- make-x-offset
- make-y-offset
- make-theta
- make-radius
- make-theta2
- make-radius2
- make-longitude
- make-latitude
- make-longitude2
- make-latitude2
- make-angle
- make-color
- make-fill
- make-stroke
- make-opacity
- make-fill-opacity
- make-stroke-opacity
- make-shape
- make-size
- make-stroke-dash
- make-stroke-width
- make-text
- make-tooltip
- make-href
- make-description
- make-detail
- make-key
- make-order
- make-facet
- make-row
- make-column

- make-axis
- make-scale
- make-bin

- =+mark-types+=
- =+data-types+=
- =+channel-types+=
- =+scale-type+=

** Ugly, low-level, flexible: =(vega-plot specification)=
:PROPERTIES:
:CUSTOM_ID: ugly-low-level-flexible-vega-plot-specification
:END:

This takes a vega-lite specification as either a plist or a =spec= object and converts it to JSON to use in the browser. This can be any plist or =spec= object.

See:

- [[file:docs/taming-vega-lite.org][Taming Vega Lite using CLOS, MOP, and Macros]]
- [[file:docs/hierarchy.org][Component Hierarchy]]
- [[https://vega.github.io/vega-lite/docs/][Vega Lite Oocumentation]], [[https://vega.github.io/vega-lite/tutorials/getting_started.html][Tutorials]], and [[https://vega.github.io/vega-lite/examples/][Examples]]


* Interactive Example
:PROPERTIES:
:CUSTOM_ID: interactive-example
:END:

The figure generated from the following should pan using mouse in the browser.

#+begin_src lisp
(vega-plot
 (make-plot
  :data (make-data :url (vega-dataset "penguins.json"))
  :mark (make-mark :type :point)
  :params (list (make-param :name "interval"
                            :select (make-select :type :interval)
                            :bind :scales)
                (make-param :name "legend"
                            :select (make-select :type :point
                                                 :fields '("Species"))
                            :bind (make-legend-binding :legend "dblclick")))
  :encoding (make-encoding :x (make-x :field "Flipper Length (mm)"
                                      :type "quantitative"
                                      :scale (list :zero nil))
                           :y (make-y :field "Body Mass (g)"
                                      :type "quantitative"
                                      :scale (list :zero nil))
                           :color (make-color :field "Species" :type "nominal")
                           :shape (make-shape :field "Species" :type "nominal"))))
#+end_src

* Common Issues
:PROPERTIES:
:CUSTOM_ID: common-issues
:END:

** Error: Message fragment too big
:PROPERTIES:
:CUSTOM_ID: error-message-fragment-too-big
:END:

This may occur duing =save-plot= and is caused due to the image exceeding the maximum expected size. Increase the limit to sidestep the problem.

#+begin_src lisp
(setf hunchensocket:*websocket-maximum-fragment-size* (expt 2 20))
#+end_src
